theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: FPiGA Project GitHub Pages
description: Radical Computer Technologies FPiGA Project Page
